#
# Copyright (c) 2018 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

# Enable the UART driver
# CONFIG_UART_ASYNC_API=y
# CONFIG_NRFX_UARTE0=y
# CONFIG_SERIAL=y

CONFIG_GPIO=y

# Make sure printk is printing to the UART console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_HEAP_MEM_POOL_SIZE=2048

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
#CONFIG_BT_DEVICE_NAME="Nordic_UART_Service"
CONFIG_BT_DEVICE_NAME="lzy_test"
CONFIG_BT_MAX_CONN=1
CONFIG_BT_MAX_PAIRED=1

# Enable the NUS service
CONFIG_BT_NUS=y

# Enable bonding
CONFIG_BT_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y

# Qingfeng 840 has no nRF52840-DK QSPI flash
CONFIG_NORDIC_QSPI_NOR=n
CONFIG_NRFX_QSPI=n

# Enable DK LED and Buttons library
CONFIG_DK_LIBRARY=y

CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
# Config logger  日志输出选择RTT或者uart，RTT需要在IDE里打开RTT Viewer，UART则直接在串口工具里查看
CONFIG_LOG=y
CONFIG_USE_SEGGER_RTT=n
CONFIG_LOG_BACKEND_RTT=n
CONFIG_LOG_BACKEND_UART=y
CONFIG_LOG_PRINTK=n

CONFIG_ASSERT=y

# 基础
#CONFIG_LOG=y 上面已经开了
CONFIG_LOG_DEFAULT_LEVEL=3
# SPI + 显示
CONFIG_SPI=y
CONFIG_DISPLAY=y
CONFIG_DISPLAY_LOG_LEVEL_INF=y
CONFIG_ST7789V=y         # 启用 Zephyr 自带 ST7789 驱动
CONFIG_ST7789V_RGB565=y  # ST7789 典型 16-bit RGB565

CONFIG_DISPLAY_LOG_LEVEL_DBG=y

# I2C + 触摸
CONFIG_I2C=y

# LVGL
CONFIG_LVGL=y
CONFIG_APP_LINK_WITH_LVGL=y
CONFIG_LV_Z_AUTO_INIT=y
CONFIG_LV_Z_MEM_POOL_SIZE=16384
CONFIG_MAIN_STACK_SIZE=4096

# Minimal widgets/fonts we use
CONFIG_LV_USE_LOG=n
CONFIG_LV_USE_LABEL=y
# Keep only label for stability test
# CONFIG_LV_USE_BUTTON=y
CONFIG_LV_FONT_MONTSERRAT_14=y
